#### Currency Controller
@baseURL = http://localhost:3000

### @name GetAllSupported
GET {{baseURL}}/currency/
Accept: application/application/json


# @name Convert
###
GET {{baseURL}}/currency/convert?from=DIU&to=USD&amount=1
Accept: application/json


### @name AddCurrency
POST {{baseURL}}/currency/add
Content-Type: application/json

{
  "currency": "SANDERS",
  "exchangeRateToUSD": 2,
  "isFictional": true

}


### @name DeleteCurrency
DELETE {{baseURL}}/currency/remove
Content-Type: application/json

{
  "currency": "DIU"
}
