@baseURL = http://localhost:3000


#### Currency Controller
# @name Coinverting-Converting
GET {{baseURL}}/currency/convert?from=BTC&to=USD&amount=1
Accept: application/json


### @name GetAllSupported
GET {{baseURL}}/currency/
Accept: application/application/json

### @name AddCurrency
POST {{baseURL}}/currency/add
Content-Type: application/json

{
  "currency": "HURB"
}


### @name DeleteCurrency
DELETE {{baseURL}}/currency/remove
Content-Type: application/json

{
  "currency": "HURB"
}
